# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

builds:
- env:
  - CGO_ENABLED=0 # this is needed otherwise the Docker image build is faulty
  goarch:
  - amd64
  goos:
  - linux

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

dockers:
# For pre releases, updating `latest` and the floating tags of the major
# version does not make sense. So only the image for the exact version should
# be pushed.
# For the lack of a less verbose solution, go templating is used to set the
# image tags to the major version or latest for normal releases. For pre
# releases, all image tags are set to the exact version. This will result in
# having the same image tag tree times in the list. This is fine to do as the
# image will be built only once and tagging is a cheap operation.
- image_templates:
  #- "docker.io/ccremer/k8up:v{{ .Version }}"
  - "quay.io/ccremer/k8up:v{{ .Version }}"

  # - "docker.io/ccremer/k8up:{{ if .Prerelease }}v{{ .Version }}{{ else }}v{{ .Major }}{{ end }}"
  - "quay.io/ccremer/k8up:{{ if .Prerelease }}v{{ .Version }}{{ else }}v{{ .Major }}{{ end }}"

  # - "docker.io/ccremer/k8up:{{ if .Prerelease }}v{{ .Version }}{{ else }}latest{{ end }}"
  - "quay.io/ccremer/k8up:{{ if .Prerelease }}v{{ .Version }}{{ else }}latest{{ end }}"

release:
  prerelease: auto

  github:
    owner: ccremer
    name: k8up
  extra_files:
  - glob: ./k8up-crd*.yaml
